version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    env_file: docker.env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/playthis
    ports:
      - "3000:3000"
    links:
      - db
