production:
  adapter: redis
  url: redis://redistogo:89b7adc2b02431cc4dafddeb0a549228@sculpin.redistogo.com:10353/

development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async
